### ISSUE TITLE
/contexts & sessionId

### ISSUE THREAD

**Issue by paranoida** [marcossegovia/apiai-go#3]
Hey,

Actually it's more like a question because I have a feeling that something is not right. Here we go:

I started working with `/context` end-point and I've seen that you implemented all methods that API.ai provides with (https://docs.api.ai/docs/contexts). When I looked into `DELETE` method is says:

```
Deletes all contexts from the specified session.

Query Parameters
sessionId – session Id
```

but in your method I cannot pass `sessionId` (which API.ai returns when I send a request).

Seems like the `SessionID` that I had to configure at the very beginning is not the one that I have to use with `DELETE`. My understanding of `sessionId` here is a unique identifier for each "client" which is a user, not bot – so there is no need to generate it at the very beginning.

What do you think about it?

**Comment by marcossegovia** [comment]
Hi @paranoida
Sorry for the delay.
I think you're right. I guess initially my point was not to make library consumers have to pass the sessionId every time, now I see there is no other way as It eventually will handle lots of concurrency user sessions using the same api client.
Let me a day and you can take it for granted.

**Comment by marcossegovia** [comment]
@paranoida this commit https://github.com/marcossegovia/apiai-go/commit/c47f5f40dc3b34d1ffa0481bf35b2a0e49014165 should resolve this issue. As you found out this problem I'll be pleased to know whether this fixes the problem or should be improved in terms of code readability or usage.
Thanks m8 !

**Comment by paranoida** [comment]
Hey,

Seems like it solved my problem 👍 

Thanks!

**Comment by marcossegovia** [comment]
Merging today and releasing a new version.

**Comment by marcossegovia** [comment]
This should be fix with https://github.com/marcossegovia/apiai-go/releases/tag/v0.3.0-beta
